import datetime
import json
import os
import anthropic
from dotenv import load_dotenv

load_dotenv()


ticket = input("Please enter the customer's support ticket: ")

with open("ticket_data.json", "r") as f:
    existing_tickets = json.load(f)
# Ticket counter to assign unique ticket numbers, in a real system this would be generated by the database or ticketing system
if existing_tickets:
    ticket_counter = max(t["ticket_number"] for t in existing_tickets) + 1
else:
    ticket_counter = 1


current_ticket_time = datetime.datetime.now().isoformat()

client = anthropic.Anthropic(api_key=os.getenv("CLAUDE_API_KEY"))
try:
    messages = [{"role": "user", "content": ticket}]
    thinking = True
    while thinking:
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            system="""You are a support agent. First decide if you have enough information to solve the ticket. If If not, respond with ONLY: NEED_INFO: [one specific question]. If you have enough info, respond with ONLY: RESOLVED: [your answer]
            Our system is a travel and expense report system, each system is created indivually for each company.""",
            messages=messages,
        )
        response = message.content[0].text

        if response.startswith("NEED_INFO:"):
            # extract the question and ask user for more info
            question = response.replace("NEED_INFO:", "").strip()
            followup = input(f"\nClaude needs more info: {question}\nYour answer: ")
            # add claude question to messages
            messages.append({"role": "assistant", "content": response})
            # add user answer to messages
            messages.append({"role": "user", "content": followup})

            # # then send again with full context
            # message = client.messages.create(
            #     model="claude-haiku-4-5-20251001",
            #     max_tokens=1024,
            #     system="""You are a support agent. First decide if you have enough information to solve the ticket. If If not, respond with ONLY: NEED_INFO: [one specific question]. If you have enough info, respond with ONLY: RESOLVED: [your answer]. Answer respectfully and professionally, with a human-like tone.""",
            #     messages=[
            #         {
            #             "role": "user",
            #             "content": f"{ticket}\nCustomer's answer to follow-up question: {followup}",
            #         }
            #     ],
            # )
            # print(message.content[0].text)
        elif response.startswith("RESOLVED:"):
            print(response.replace("RESOLVED:", "").strip())
            thinking = False

    # creating a JSON object to store complete ticket - ticket_number, user, status, issue, conversation_history, final_answer, timestamp, ?comapny, support_handler
    ticket_data = {
        "ticket_number": ticket_counter,
        "user": "customer_name",  # this can be extracted from the ticket or asked as a follow-up question
        "status": "resolved",
        "issue": ticket,
        "conversation_history": messages,
        "final_answer": response.replace("RESOLVED:", "").strip(),
        "timestamp": current_ticket_time,  # this can be generated dynamically
    }

    # ticket_counter += 1

    # Save ticket data so var so we could add new tickets to the same file without overwriting
    with open("ticket_data.json", "r") as f:
        tickets_data = json.load(f)
        tickets_data.append(ticket_data)

    with open("ticket_data.json", "w") as f:
        json.dump(tickets_data, f, indent=4)


except Exception as e:
    print("Error communicating with Claude API: ", e)
